---

- name: Install ocis packages
  ansible.builtin.package:
    name: '{{ ocis_packages }}'
    state: present

- name: Create ocis system group
  ansible.builtin.group:
    name: '{{ ocis_group }}'
    system: true
    state: present

- name: Create ocis system user
  ansible.builtin.user:
    name: '{{ ocis_user }}'
    append: false
    comment: 'ownCloud Infinite Scale'
    create_home: false
    expires: -1
    group: '{{ ocis_group }}'
    home: '{{ ocis_data_path }}'
    password: '!'
    remove: false
    shell: /sbin/nologin
    system: true
    update_password: always
    state: present

- name: Create ocis data directory
  ansible.builtin.file:
    path: '{{ ocis_data_path }}'
    owner: '{{ ocis_user }}'
    group: '{{ ocis_group }}'
    mode: '0750'
    state: directory

- name: Create ocis config directory
  ansible.builtin.file:
    path: '{{ ocis_config_path }}'
    owner: '{{ ocis_user }}'
    group: '{{ ocis_group }}'
    mode: '0755'
    state: directory

- name: Download, verify and place ocis binary
  ansible.builtin.get_url:
    url: '{{ ocis_download_url }}/{{ ocis_release }}/{{ ocis_version }}/ocis-{{ ocis_version }}-linux-amd64'
    dest: '{{ ocis_bin_path }}/ocis'
    backup: false
    checksum: 'sha256:{{ ocis_download_url }}/{{ ocis_release }}/{{ ocis_version }}/ocis-{{ ocis_version }}-linux-amd64.sha256'
    force: true
    validate_certs: true
    owner: root
    group: root
    mode: '0755'

- name: Configure ocis environment config
  ansible.builtin.template:
    src: etc/ocis/ocis.env.j2
    dest: /etc/ocis/ocis.env
    owner: ocis
    group: ocis
    mode: '0640'
# notify: Restart ocis

- name: Configure ocis systemd service
  ansible.builtin.template:
    src: etc/systemd/system/ocis.service.j2
    dest: /etc/systemd/system/ocis.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd daemon

- name: Initialize ocis yaml config
  ansible.builtin.command:
    cmd: 'ocis init --insecure {{ ocis_env_insecure }} --config-path {{ ocis_config_path }}'
    creates: '{{ ocis_config_path }}/ocis.yaml'
  become: true
  become_user: '{{ ocis_user }}'

# Service related tasks do not work well in molecule idempotence tests
- name: Enable ocis
  ansible.builtin.service:
    name: ocis
    enabled: true
    state: started
  tags:
    - molecule-idempotence-notest
