---

argument_specs:
  main:
    short_description: Manages and deploys Traefik.
    options:
      traefik_acme_file:
        description:
          - File where ACME data is stored.
        type: str
        required: false
        default: '{{ traefik_config_path }}/acme.json'
      traefik_config:
        description:
          - Main configuration based on 1:1 dict copy of the intended Traefik
            config.
        type: dict
        required: false
        default: {}
      traefik_config_path:
        description:
          - Directory where to place the Traefik configs.
        type: str
        required: false
        default: /etc/traefik
      traefik_environment:
        description:
          - Systemd service environment configuration.
        type: list
        elements: str
        required: false
        default: []
      traefik_group:
        description:
          - System group used for the Traefik processes.
        type: str
        required: false
        default: traefik
      traefik_log_path:
        description:
          - Directory where to place the Traefik logs.
        type: str
        required: false
        default: /var/log/traefik
      traefik_packages:
        description:
          - List of traefik packages to install.
        type: list
        elements: str
        required: false
        default:
          - traefik
      traefik_provider:
        description:
          - Provider configuration based on 1:1 dict copy of the intended
            Traefik config.
        type: dict
        required: false
        default: {}
      traefik_user:
        description:
          - System user used for the Traefik processes.
        type: str
        required: false
        default: traefik
