---

name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Publish collection
        run: |
          ansible-galaxy role import karras ansible-role_ocis --token=${{ secrets.GALAXY_API_KEY }} 
